name: Update Catalog
on:
  push:
    branches:
      - "**"
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
        working-directory: catalog
      - run: node scripts/update-catalog-index.js
        working-directory: catalog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Ensure docs folder exists and move index.html
        run: |
          mkdir -p docs
          mv catalog/index.html docs/
      - name: Update README with correct GitHub Pages owner
        run: |
          OWNER=${GITHUB_REPOSITORY_OWNER}
          # Replace only the owner part in the URL
          sed -i -E "s|(https://)[^./]+(\.github\.io/marketplace/docs/index.html)|\1$OWNER\2|g" README.md
      - run: git add docs/index.html catalog/plugins-data.json README.md
      - run: git config user.name "GitHub Actions"
      - run: git config user.email "actions@github.com"
      - run: git commit -m "Update catalog docs/index.html and README" || echo "No changes"
      - run: git push
