name: Update Catalog
on:
  push:
    branches:
      - "**"
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
        working-directory: catalog
      - run: node scripts/update-catalog-index.mjs
        working-directory: catalog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: git add index.html package-data.json
        working-directory: catalog
      - run: git config user.name "GitHub Actions"
      - run: git config user.email "actions@github.com"
      - run: git commit -m "Update catalog" || echo "No changes"
      - run: git push
